# Generated by Django 5.1.1 on 2024-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ref",
            field=models.CharField(default=234, max_length=255),
            preserve_default=False,
        ),
    ]
