# Generated by Django 5.1.1 on 2024-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="notification_any_news",),
        migrations.RemoveField(
            model_name="customuser", name="notification_changes_made_to_account",
        ),
        migrations.RemoveField(model_name="customuser", name="notification_type",),
        migrations.AddField(
            model_name="profile",
            name="notification_any_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_changes_made_to_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_type",
            field=models.CharField(
                choices=[("sms", "SMS"), ("email", "Email"), ("none", "None")],
                default="sms",
                max_length=10,
            ),
        ),
    ]
