# Generated by Django 5.1.1 on 2024-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_customuser_notification_any_news_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="notification_type",
            field=models.CharField(
                choices=[("sms", "SMS"), ("email", "Email"), ("none", "None")],
                default="email",
                max_length=10,
            ),
        ),
    ]
